pipeline {
	agent { label 'fdc-jenkins'}

    stages {
        stage('stage-01') {
            agent none
            steps {
                echo 'Building..'
                sh '''	echo  "stage-01 steps" 
				
				cd /opt/alam-workspace
				./test.sh
				'''
            }
        }
		
	}

    post {
        success {
            echo 'This will run only if successful'
        }
    }
}